name: Docker
on: [pull_request, push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out to Code
              uses: actions/checkout@v4
            - name: Docker Log in
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Push to docker Hub
              uses: docker/build-push-action@v1
              with:
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_REPO_NAME }}:sample
                
    build-and-push-image:
        runs-on: ubuntu-latest 
        permissions: 
            contents: read
            packages: write 
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Build container image
              uses: docker/build-push-action@v3
              with: 
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
                registry: docker.pkg.github.com
                repository: ${{ github.repository }}/python-flask-github-action-package
                tag_with_sha: true
                tag_with_ref: true              